version: "3"

services:
  backend-bff:
    build:
      context: ./backend/bff/
      target: "base"
    command: sh -c "yarn && yarn start:dev"
    container_name: backend-bff
    ports:
      - 3000:3000
    environment:
      REDIS_URL: redis://redis:6379

  backend-users:
    build:
      context: ./backend/users/
      target: "base"
    command: sh -c "yarn && yarn start:dev"
    container_name: backend-users
    environment:
      REDIS_URL: redis://redis:6379

  backend-profiles:
    build:
      context: ./backend/profiles/
      target: "base"
    command: sh -c "yarn && yarn start:dev"
    container_name: backend-profiles
    environment:
      REDIS_URL: redis://redis:6379

  redis:
    build: ./redis/
    container_name: redis
    ports:
      - 6379:6379

  frontend:
    build:
      context: ./frontend/
      target: "base"
    command: sh -c "yarn && yarn dev"
    container_name: frontend
    environment:
      NEXT_PUBLIC_API: http://localhost:3000
    ports:
      - 3001:3001
    volumes:
      - $PWD/frontend:/app

networks:
  sites-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16