defaults: &defaults
  docker:
    - image: patrickcoutinho/cloud-devops-ci

version: 2.1

orbs:
  slack: circleci/slack@4.10.1

commands:
  destroy-k8s-environment:
    description: Destroy k8s environment on smoke test fail
    steps:
      - run:
          name: Destroy k8s environment on fail
          when: on_fail
          command: |
            make destroy-k8s-environment
  destroy-frontend-environment:
    description: Destroy front-end cloudformation
    parameters:
      version:
        type: string
    steps:
      - run:
          name: Destroy front-end environment
          when: on_fail
          command: |
            aws s3 rm s3://cloud-devops-capstone-<<parameters.version>> --recursive
            aws cloudformation delete-stack \
                --stack-name cloud-devops-capstone-<<parameters.version>> \

jobs:
  install-project:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1.1.0-deps-{{ checksum "yarn.lock" }}
            - v1.1.0-deps-
      - run:
          name: Install project
          command: |
            yarn
      - save_cache:
          key: v1.1.0-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - backend/bff/node_modules
            - backend/users/node_modules
            - backend/profiles/node_modules
            - frontend/node_modules

  run-tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1.1.0-deps-{{ checksum "yarn.lock" }}
            - v1.1.0-deps-
      - run:
          name: Run all tests
          command: |
            make test
      - slack/notify:
          template: basic_fail_1
          event: fail

  run-lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1.1.0-deps-{{ checksum "yarn.lock" }}
            - v1.1.0-deps-
      - run:
          name: Run lint
          command: |
            make lint
      - slack/notify:
          template: basic_fail_1
          event: fail

  notify-success:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1.1.0-deps-{{ checksum "yarn.lock" }}
            - v1.1.0-deps-
      - slack/notify:
          template: basic_success_1
          event: always

  update-version:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1.1.0-deps-{{ checksum "yarn.lock" }}
            - v1.1.0-deps-
      - run:
          name: Update version
          command: |
            npx semantic-release
      - slack/notify:
          template: basic_fail_1
          event: fail

  build-images:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build and push Docker images
          command: |
            export NEW_VERSION=$(git describe --tags --abbrev=0)
            echo NEW_VERSION: $NEW_VERSION

            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin

            make build-docker-images version=$NEW_VERSION
            make push-docker-images version=$NEW_VERSION
      - slack/notify:
          template: basic_fail_1
          event: fail

  create-k8s-green-deployment:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploy images to k8s cluster
          command: |
            make create-k8s-deployment svc_env=green
      - slack/notify:
          template: basic_fail_1
          event: fail

  smoke-test-k8s-green-deployment:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Perform smoke test
          command: |
            make smoke-test-k8s-green-deployment svc_env=green
      - slack/notify:
          template: basic_fail_1
          event: fail
      - destroy-k8s-environment

  deploy-frontend-infra:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            export NEW_VERSION=$(git describe --tags --abbrev=0)
            echo NEW_VERSION: $NEW_VERSION

            aws cloudformation deploy \
              --template-file ./cloudformation/frontend/cloudfront.yml \
              --stack-name "cloud-devops-capstone-${NEW_VERSION}" \
              --tags project=cloud-devops-capstone \
              --parameter-overrides version="${NEW_VERSION}"
      - slack/notify:
          template: basic_fail_1
          event: fail
      - destroy-k8s-environment
      - destroy-frontend-environment

  update-k8s-blue-deployment:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploy images to k8s cluster
          command: |
            make update-k8s-service svc_env=blue
      - slack/notify:
          template: basic_fail_1
          event: fail

  cleanup-k8s-green-deployment:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Cleanup green service/deployment
          command: |
            make cleanup-k8s-deployment
      - slack/notify:
          template: basic_fail_1
          event: fail

workflows:
  integration:
    jobs:
      - install-project
      - run-tests:
          requires: [install-project]
          context:
            - teste
      - run-lint:
          requires: [install-project]
          context:
            - teste
      - notify-success:
          requires: [run-tests, run-lint]
          context:
            - teste
          filters:
            branches:
              ignore: master
      - update-version:
          requires: [run-tests, run-lint]
          context:
            - teste
          filters:
            branches:
              only: master

  deployment:
    jobs:
      - build-images:
          context:
            - teste
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - create-k8s-green-deployment:
          requires: [build-images]
          context:
            - teste
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - smoke-test-k8s-green-deployment:
          requires: [create-k8s-green-deployment]
          context:
            - teste
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy-frontend-infra:
          requires: [smoke-test-k8s-green-deployment]
          context:
            - teste
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - update-k8s-blue-deployment:
          requires: [smoke-test-k8s-green-deployment]
          context:
            - teste
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - cleanup-k8s-green-deployment:
          requires: [update-k8s-blue-deployment]
          context:
            - teste
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
