apiVersion: v1
kind: Service

metadata:
  name: cloud-devops-backend-bff-lb

spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: cloud-devops-backend-bff
