apiVersion: v1
kind: Service

metadata:
  name: cloud-devops-backend-users-lb

spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: cloud-devops-backend-users
