apiVersion: v1
kind: Service

metadata:
  name: cloud-devops-backend-profiles-svc

spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: cloud-devops-backend-profiles
