apiVersion: v1
kind: Service

metadata:
  name: cloud-devops-backend-users-svc-{{SVC_ENV}}

spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: cloud-devops-backend-users-{{NEW_VERSION_NAME}}
