apiVersion: v1
kind: Service

metadata:
  name: cloud-devops-redis-lb

spec:
  type: LoadBalancer
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: cloud-devops-redis
